"""``uv run balance``: play the balance matrix and write the Markdown report.

    uv run balance --seeds 50 --out ../docs/2026-09-27-b4-balance-and-juice/report.md
    uv run balance --seeds 20 --maps outpost --strategies smart,casual --hp outpost=1.1
    uv run balance --seeds 50 --abilities cryo_bomb,napalm   # + smart/casual with each
"""

from __future__ import annotations

import argparse
import json
import time
from pathlib import Path

from gf_tools.balance import report, runner

STRATEGIES = ["smart", "casual", "no_ability", "no_links", "cycle", "heavy", "light", "mixed",
              "no_loot"]


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawTextHelpFormatter)
    p.add_argument("--seeds", type=int, default=50)
    p.add_argument("--maps", default=",".join(report.SECTOR_PROFILES))
    p.add_argument("--strategies", default=",".join(STRATEGIES))
    p.add_argument("--jobs", type=int, default=None)
    p.add_argument("--abilities", default="",
                   help="special attacks to compare: adds smart+ID and casual+ID cells per map")
    p.add_argument("--hp", default="", help="per-map hp multipliers, e.g. outpost=1.1,canyon=0.9")
    p.add_argument("--out", type=Path, default=Path("balance-report.md"))
    p.add_argument("--records", type=Path, default=None, help="also save the raw records (JSON)")
    a = p.parse_args(argv)
    hp = {k: float(v) for k, v in (kv.split("=") for kv in a.hp.split(",") if kv)}
    cells = [(m, report.SECTOR_PROFILES.get(m, "T0"), s)
             for m in a.maps.split(",") for s in a.strategies.split(",")]
    cells += [(m, report.SECTOR_PROFILES.get(m, "T0"), f"{s}+{ab}")
              for m in a.maps.split(",") for ab in a.abilities.split(",") if ab
              for s in ("smart", "casual")]
    start = time.time()
    records = runner.run_matrix(cells, a.seeds, a.jobs, hp)
    stats = report.aggregate(records)
    checks = report.check_targets(stats)
    notes = (f"_{len(records)} runs, seeds 1–{a.seeds}, {time.time() - start:.0f} s; "
             f"hp multipliers: {hp or 'none'}. Generated by `uv run balance`._")
    a.out.write_text(report.render(stats, checks, "Balance report", notes))
    if a.records:
        a.records.write_text(json.dumps(records))
    for c in checks:
        print(("OK   " if c.ok else "MISS ") + c.name + ": " + c.detail)
    print(f"wrote {a.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
