class_name Art
extends RefCounted
## Where the game's art lives, in one place. Sources are SVG in res://art/ (generated by
## tools/: `uv run gen-art`), rasterized by Godot at 2x their art-unit size, so every sprite is
## drawn at scale 0.5 (SCALE) to land at its size in field units.

const SCALE: float = 0.5

static var _cache: Dictionary[String, Texture2D] = {}


## The texture for `key` ("enemies/grunt", "units/mg", …), or null if there is none.
static func tex(key: String) -> Texture2D:
	if _cache.has(key):
		return _cache[key]
	var path: String = "res://art/%s.svg" % key
	var t: Texture2D = load(path) if ResourceLoader.exists(path) else null
	_cache[key] = t
	return t


## Size of `key` in field units (texture pixels × SCALE).
static func size(key: String) -> Vector2:
	var t: Texture2D = tex(key)
	return t.get_size() * SCALE if t != null else Vector2.ZERO


## A quad of `size` centred on the origin with UVs 0..1 (for textured MultiMeshes; built by
## hand so the UV orientation is explicit rather than QuadMesh's 3D convention).
static func quad(size: Vector2) -> ArrayMesh:
	var h: Vector2 = size / 2.0
	var arrays: Array = []
	arrays.resize(Mesh.ARRAY_MAX)
	arrays[Mesh.ARRAY_VERTEX] = PackedVector2Array([Vector2(-h.x, -h.y), Vector2(h.x, -h.y),
			Vector2(h.x, h.y), Vector2(-h.x, -h.y), Vector2(h.x, h.y), Vector2(-h.x, h.y)])
	arrays[Mesh.ARRAY_TEX_UV] = PackedVector2Array([Vector2(0, 0), Vector2(1, 0), Vector2(1, 1),
			Vector2(0, 0), Vector2(1, 1), Vector2(0, 1)])
	var mesh := ArrayMesh.new()
	mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, arrays)
	return mesh


## A material that adds light instead of covering (glows, tracers, flashes).
static func additive() -> CanvasItemMaterial:
	var m := CanvasItemMaterial.new()
	m.blend_mode = CanvasItemMaterial.BLEND_MODE_ADD
	return m


## Draw `key` centred at `pos` on `ci`, rotated and scaled (1.0 = its field size).
static func draw(ci: CanvasItem, key: String, pos: Vector2, rot: float = 0.0,
		scl: float = 1.0, modulate: Color = Color.WHITE) -> void:
	var t: Texture2D = tex(key)
	if t == null:
		return
	ci.draw_set_transform(pos, rot, Vector2.ONE * scl * SCALE)
	ci.draw_texture(t, -t.get_size() / 2.0, modulate)
	ci.draw_set_transform(Vector2.ZERO, 0.0, Vector2.ONE)
