class_name Art
extends RefCounted
## Where the game's art lives, in one place. Sources are SVG in res://art/ (generated by
## tools/: `uv run gen-art`). Sprites are rasterized at 4x their art-unit size and drawn at
## SPRITE_SCALE, so they stay sharp on 1440p phones and tablets (the 540-wide view is shown at up
## to ~2.9x); mipmaps keep them clean when shrunk on small windows. Full-screen art under
## field/ is 2x (FIELD_SCALE): at 4x a ground alone would take ~30 MB of video memory. The
## generator's RASTER/FIELD_RASTER (tools/src/gf_tools/art/svg.py) is the other half of this rule.

const FIELD_SCALE: float = 0.5
const SPRITE_SCALE: float = 0.25

static var _cache: Dictionary[String, Texture2D] = {}


## The texture for `key` ("enemies/grunt", "units/mg", …), or null if there is none.
static func tex(key: String) -> Texture2D:
	if _cache.has(key):
		return _cache[key]
	var path: String = "res://art/%s.svg" % key
	var t: Texture2D = load(path) if ResourceLoader.exists(path) else null
	_cache[key] = t
	return t


## Field units per texture pixel for `key`: FIELD_SCALE for field/ art, SPRITE_SCALE otherwise.
static func scale_of(key: String) -> float:
	return FIELD_SCALE if key.begins_with("field/") else SPRITE_SCALE


## Size of `key` in field units (texture pixels × its scale).
static func size(key: String) -> Vector2:
	var t: Texture2D = tex(key)
	return t.get_size() * scale_of(key) if t != null else Vector2.ZERO


## A quad of `size` centred on the origin with UVs 0..1 (for textured MultiMeshes; built by
## hand so the UV orientation is explicit rather than QuadMesh's 3D convention).
static func quad(size: Vector2) -> ArrayMesh:
	var h: Vector2 = size / 2.0
	var arrays: Array = []
	arrays.resize(Mesh.ARRAY_MAX)
	arrays[Mesh.ARRAY_VERTEX] = PackedVector2Array([Vector2(-h.x, -h.y), Vector2(h.x, -h.y),
			Vector2(h.x, h.y), Vector2(-h.x, -h.y), Vector2(h.x, h.y), Vector2(-h.x, h.y)])
	arrays[Mesh.ARRAY_TEX_UV] = PackedVector2Array([Vector2(0, 0), Vector2(1, 0), Vector2(1, 1),
			Vector2(0, 0), Vector2(1, 1), Vector2(0, 1)])
	var mesh := ArrayMesh.new()
	mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, arrays)
	return mesh


## A material that adds light instead of covering (glows, tracers, flashes).
static func additive() -> CanvasItemMaterial:
	var m := CanvasItemMaterial.new()
	m.blend_mode = CanvasItemMaterial.BLEND_MODE_ADD
	return m


## Draw `key` centred at `pos` on `ci`, rotated and scaled (1.0 = its field size).
static func draw(ci: CanvasItem, key: String, pos: Vector2, rot: float = 0.0,
		scl: float = 1.0, modulate: Color = Color.WHITE) -> void:
	var t: Texture2D = tex(key)
	if t == null:
		return
	ci.draw_set_transform(pos, rot, Vector2.ONE * scl * scale_of(key))
	ci.draw_texture(t, -t.get_size() / 2.0, modulate)
	ci.draw_set_transform(Vector2.ZERO, 0.0, Vector2.ONE)
